<a href="https://colab.research.google.com/github/felipemontano10/computervision/blob/master/hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### COMPSCI 527 - Spring 2020
## Homework 2
**Collaborators:**


> Haozhe Zhang

> Felipe Montano-Campos













**Problem 1.1**

Let's recall thta a two-dimensional kernel is separable if it can be expressed as the outer product of two vectors, hence we need to solve the following equation:

$$
\begin{pmatrix}w_1\\
w_2\\
w_3
\end{pmatrix}\times 
\begin{pmatrix}
r_1 &r_2&r_3
\end{pmatrix}=
\begin{pmatrix}
a &-2&b\\
c &3&d\\
2 &1&-4
\end{pmatrix}=H
$$

So we need to solve the following system of equation:

\begin{equation}
    w_1r_1=a \quad\quad \text{(1)}
\end{equation}

\begin{equation}
    w_1r_2=-2 \quad\quad \text{(2)}
\end{equation}

\begin{equation}
    w_1r_3=b \quad\quad \text{(3)}
\end{equation}

\begin{equation}
    w_2r_1=c \quad\quad \text{(4)}
\end{equation}

\begin{equation}
    w_2r_2=3 \quad\quad \text{(5)}
\end{equation}

\begin{equation}
    w_2r_3=d \quad\quad \text{(6)}
\end{equation}

\begin{equation}
    w_3r_1=2 \quad\quad \text{(7)}
\end{equation}

\begin{equation}
    w_3r_2=1 \quad\quad \text{(8)}
\end{equation}

\begin{equation}
    w_3r_3=-4 \quad\quad \text{(9)}
\end{equation}

If we combine (1), (7), (3), and (9) we get
$$
b = -2a
$$
If we combine (2), (5), (3), and (6) we get
$$
d = 3a
$$
If we combine (1), (4), (2) and (5) we get
$$
c= -\frac{3}{2}a
$$
Finally, if we combine (4), (7), (5) and (8) we get 
$$
c=6
$$


Substituting $c$ in all the previous expressions we get that $a=-4$, $b=8$, $c=6$ and, $d=-12$.



In [9]:
A = [[-4, -2, 8], 
    [6, 3, -12],
     [2, 1, -4]]


from numpy.linalg import matrix_rank
rank = matrix_rank(A)
print("we get a matrix with rank:") 
rank

we get a matrix with rank:


1

**Problem 1.2**

Compute the "valid" convolution $V$, "full" convolution $F$, and "same" convolution $S$ of image 
$$I=
\begin{pmatrix}
2 & -1 & 3\\
1 & 0 & 4 
\end{pmatrix} \quad \text{with the kernel} \quad
H=\begin{pmatrix}
1 & 0\\
2 & 1
\end{pmatrix}
$$

Let's recall that to calculate the convolution of $I$ we will have to flip the kernel 180 degrees
$$
\begin{pmatrix}
1 & 2\\
0 & 1
\end{pmatrix}
$$

and then, depending on how we define de image boundaries, we slice the kernel across the image, make a point-wise multiplication and sum the terms.


**The valid convolution**

The output consists only of those elements that do not rely on the zero-padding, hence we have:

$$
\begin{pmatrix}
2 & -1 & 3\\
1 & 0 & 4 
\end{pmatrix}\circledast
\begin{pmatrix}
1 & 2\\
0 & 1
\end{pmatrix}=
\begin{pmatrix}
0 & 9\\
\end{pmatrix}
$$

**The same convolution**

The output is the same size as the input image. As defined in the instruction we have:

$$
S_{-}=\begin{pmatrix}
0 & 0 & 0 & 0\\
0 & 2 & -1 & 3\\
0 & 1 & 0 & 4 
\end{pmatrix}\circledast
\begin{pmatrix}
1 & 2\\
0 & 1
\end{pmatrix}=
\begin{pmatrix}
2 & -1 & 3 \\
5 & 0 & 9
\end{pmatrix}
$$



$$
S_{+}=\begin{pmatrix}
 2 & -1 & 3 & 0\\
 1 & 0 & 4 & 0\\
0 & 0 & 0 & 0\\
\end{pmatrix}\circledast
\begin{pmatrix}
1 & 2\\
0 & 1
\end{pmatrix}=
\begin{pmatrix}
0 & 9 & 3 \\
1 & 8 & 4
\end{pmatrix}
$$

**The full covolution**

The output is the full discrete linear convolution of the inputs.


$$
\begin{pmatrix}
0 & 0 & 0 & 0 & 0\\
0 & 2 & -1 & 3 & 0\\
0 & 1 & 0 & 4 & 0\\
0 & 0 & 0 & 0 & 0\\
\end{pmatrix}\circledast
\begin{pmatrix}
1 & 2\\
0 & 1
\end{pmatrix}=
\begin{pmatrix}
2 & -1 & 3 & 0 \\
5 & 0 & 9 & 3\\
2 & 1 & 8 & 4
\end{pmatrix}
$$

In [12]:
from scipy import signal
from scipy import misc

I = [[2, -1, 3],
     [1, 0, 4]]

H = [[1,0],
     [2,1]]



valid = signal.convolve2d(I, H, boundary='fill', mode='valid')
print(valid)
same = signal.convolve2d(I, H, boundary='fill', mode='same')
print(same)
full = signal.convolve2d(I, H, boundary='fill', mode='full')
print(full)


[[0 9]]
[[ 2 -1  3]
 [ 5  0  9]]
[[ 2 -1  3  0]
 [ 5  0  9  3]
 [ 2  1  8  4]]


**Problem 1.3**

A 10 by 15 image is convolved by "valid" convolution with a 2 by 3 non-separable kernel. How many multiplications are involved? Your final answer should be a single integer. 

**R.** Let's recall that per pixel we have about $2mn$ operation, where in our particular case $m=7$, $n=5$, hence per pixel we have 35 operations and we have 150 pixels. So, the total number of multiplications is 5250